model_class: lg
data:
  D: 10
  K: 20
  N: 1000
  alpha: 2
  prop_missing: 0.1
  tau_v: 0.25
  tau_x: 25
model:
  K: 20
run:
  max_time: 10000
  num_datasets: 4
  num_init_params: 4
  num_restarts: 5  
num_particles:
  - 5
  - 10
  - 20
  - 50
