model_class: pyclone
data:
  D: 10
  K: 12
  N: 200
  alpha: 2
model:
  K: 12
run:
  max_time: 10000
  num_datasets: 4
  num_init_params: 4
  num_restarts: 5
num_particles:
  - 5
  - 10
  - 20
  - 50
