sampler_contrast:
  pg:
    annealing_power:
    - 0.0
    - 1.0
    - 2.0
    - 3.0
sampler_shared:
  pg:
    num_particles: 20
    resample_scheme: multinomial
    resample_threshold: 0.5
    test_path: zeros
sampler:
  gibbs:
    updater: g