sampler_contrast:
  pg:
    resample_threshold:
    - 0.0
    - 0.25
    - 0.5
    - 0.75
    - 1.0
sampler_shared:
  pg:
    annealing_power: 1.0
    num_particles: 20
    resample_scheme: multinomial
    test_path: zeros
sampler:
  gibbs:
    updater: g