data:
  D: 10
  K: 5
  N: 100
  alpha: 2
model:
  K: 5
run:
  max_time: 10
  num_datasets: 2
  num_init_params: 2
  num_restarts: 2
sampler:
  gibbs:
    updater: g
  row-gibbs:
    updater: rg
  pg:
    updater: pg
    kwargs:
      annealing_power: 1.0
      num_particles: 20
      resample_scheme: multinomial
      resample_threshold: 0.5
      test_path: zeros
  dpf:
    updater: dpf
    kwargs:
      annealing_power: 1.0
      num_particles: 20
      test_path: zeros