data:
  D: 10
  K: 20
  N: 100
  alpha: 2
  prop_missing: 0.1
  tau_v: 0.25
  tau_x: 25
model:
  K: 20
run:
  max_time: 1000
  num_datasets: 4
  num_init_params: 4
  num_restarts: 5
sampler:
  dpf-num_particles-10:
    annealing_power: 1.0
    num_particles: 10
    test_path: zeros
    updater: dpf
  dpf-num_particles-100:
    annealing_power: 1.0
    num_particles: 100
    test_path: zeros
    updater: dpf
  dpf-num_particles-2:
    annealing_power: 1.0
    num_particles: 2
    test_path: zeros
    updater: dpf
  dpf-num_particles-20:
    annealing_power: 1.0
    num_particles: 20
    test_path: zeros
    updater: dpf
  dpf-num_particles-5:
    annealing_power: 1.0
    num_particles: 5
    test_path: zeros
    updater: dpf
  dpf-num_particles-50:
    annealing_power: 1.0
    num_particles: 50
    test_path: zeros
    updater: dpf
  gibbs:
    updater: g
